### ISSUE TITLE
How to use this image to expose volumes to other containers?

### ISSUE THREAD

**Issue by marcopeg** [justincormack/nsenter1#4]
Hi Justin, I'm trying to tail the docker logs from a Node app.

Of course the problem seems to access the files itself, and your project looks a promising step toward a solution.

Is there a way to have your project expose `/var/lib/docker` as a volume that could be inherited by other containers?

**Comment by justincormack** [comment]
Why can't you just do `docker run -v /var/lib/docker:/var/libdocker ...` to share this?

**Comment by marcopeg** [comment]
Hej, I'm not sure what do you mean. Here is a pseudo-coded docker-compose that express what I aim for:

```
services:

  nsenter1:
    image: justincormack/nsenter1
    ...

  myservice:
     image: foo
     volumes_from: nsenter
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
```

"myservice" should then be able to access host's docker info and logs even on MacOS.
Right now I've build a small utility that tries to tail the log files (on linux) and falls back on child process spawning a `docker logs -f` that give or takes works, but I read around is less efficient compared to tailing the files.

Marco
